version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: akironseo_postgres
    restart: always
    environment:
      POSTGRES_USER: akiron_user
      POSTGRES_PASSWORD: akiron_password
      POSTGRES_DB: akironseo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
