using System.Text.RegularExpressions;
using AkironSeo.Application.Common.Interfaces;

namespace AkironSeo.Infrastructure.Services;

public class RobotsTxtAuditorService : IRobotsTxtAuditorService
{
    private readonly HttpClient _httpClient;

    public RobotsTxtAuditorService(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<RobotsTxtAuditDto> AuditRobotsTxtAsync(string domainUrl, CancellationToken cancellationToken = default)
    {
        var cleanDomain = domainUrl.Trim();
        if (!cleanDomain.StartsWith("http://") && !cleanDomain.StartsWith("https://"))
        {
            cleanDomain = "https://" + cleanDomain;
        }

        var robotsUri = new Uri(new Uri(cleanDomain), "/robots.txt");
        string rawRobotsTxt = "";
        bool hasRobotsTxt = false;

        try
        {
            var response = await _httpClient.GetAsync(robotsUri, cancellationToken);
            if (response.IsSuccessStatusCode)
            {
                rawRobotsTxt = await response.Content.ReadAsStringAsync(cancellationToken);
                hasRobotsTxt = true;
            }
        }
        catch
        {
            // robots.txt unreachable
        }

        var botsToCheck = new Dictionary<string, (string Agent, string Description)>
        {
            { "OpenAI GPTBot", ("GPTBot", "Used by OpenAI to crawl web content for ChatGPT AI models.") },
            { "ChatGPT User", ("ChatGPT-User", "Used by ChatGPT when users perform live web browsing.") },
            { "Anthropic Claude", ("ClaudeBot", "Used by Anthropic to train and fetch web content for Claude AI.") },
            { "Perplexity AI", ("PerplexityBot", "Used by Perplexity AI search engine for live answers.") },
            { "Google Extended", ("Google-Extended", "Used by Google to train Gemini AI models.") },
            { "ByteDance Spider", ("Bytespider", "Used by ByteDance / TikTok AI models.") }
        };

        var botStatuses = new List<AiBotStatusDto>();

        foreach (var (botName, (agent, desc)) in botsToCheck)
        {
            var status = CheckBotStatus(rawRobotsTxt, agent);
            botStatuses.Add(new AiBotStatusDto(
                BotName: botName,
                UserAgent: agent,
                Status: status,
                Description: desc
            ));
        }

        return new RobotsTxtAuditDto(
            DomainUrl: cleanDomain,
            HasRobotsTxt: hasRobotsTxt,
            BotStatuses: botStatuses,
            RawRobotsTxt: rawRobotsTxt
        );
    }

    private static string CheckBotStatus(string robotsTxt, string userAgent)
    {
        if (string.IsNullOrWhiteSpace(robotsTxt)) return "NotSpecified";

        var lines = robotsTxt.Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries);
        bool currentSectionApplies = false;
        bool wildcardSectionApplies = false;
        bool isDisallowedForBot = false;
        bool isDisallowedForWildcard = false;

        foreach (var line in lines)
        {
            var trimmed = line.Trim();
            if (trimmed.StartsWith("#")) continue;

            if (trimmed.StartsWith("User-agent:", StringComparison.OrdinalIgnoreCase))
            {
                var agentVal = trimmed["User-agent:".Length..].Trim();
                currentSectionApplies = agentVal.Equals(userAgent, StringComparison.OrdinalIgnoreCase);
                if (agentVal == "*") wildcardSectionApplies = true;
                else if (!currentSectionApplies) wildcardSectionApplies = false;
            }
            else if (trimmed.StartsWith("Disallow:", StringComparison.OrdinalIgnoreCase))
            {
                var path = trimmed["Disallow:".Length..].Trim();
                if (path == "/")
                {
                    if (currentSectionApplies) isDisallowedForBot = true;
                    if (wildcardSectionApplies) isDisallowedForWildcard = true;
                }
            }
        }

        if (isDisallowedForBot) return "Disallowed";
        if (isDisallowedForWildcard && !isDisallowedForBot) return "Disallowed";
        return "Allowed";
    }

    public string GenerateOptimizedRobotsTxt(RobotsTxtPresetEnum preset, string domainUrl, string? sitemapUrl = null)
    {
        var cleanDomain = domainUrl.TrimEnd('/');
        if (!cleanDomain.StartsWith("http://") && !cleanDomain.StartsWith("https://"))
        {
            cleanDomain = "https://" + cleanDomain;
        }

        var sitemap = sitemapUrl ?? $"{cleanDomain}/sitemap.xml";
        var llmsTxtUrl = $"{cleanDomain}/llms.txt";

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# ===========================================================================");
        sb.AppendLine($"# Robots.txt configured for {cleanDomain}");
        sb.AppendLine($"# Generated by AkironSeo AI Optimizer ({preset})");
        sb.AppendLine("# ===========================================================================");
        sb.AppendLine();

        switch (preset)
        {
            case RobotsTxtPresetEnum.MaxAiVisibility:
                sb.AppendLine("# 1. General Search Crawlers");
                sb.AppendLine("User-agent: *");
                sb.AppendLine("Allow: /");
                sb.AppendLine("Disallow: /admin/");
                sb.AppendLine("Disallow: /api/");
                sb.AppendLine();
                sb.AppendLine("# 2. AI Search & Direct Answer Engines (Maximum GEO Visibility)");
                sb.AppendLine("User-agent: GPTBot");
                sb.AppendLine("Allow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: ChatGPT-User");
                sb.AppendLine("Allow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: PerplexityBot");
                sb.AppendLine("Allow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: ClaudeBot");
                sb.AppendLine("Allow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: Google-Extended");
                sb.AppendLine("Allow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: Applebot-Extended");
                sb.AppendLine("Allow: /");
                break;

            case RobotsTxtPresetEnum.SearchOnlyAi:
                sb.AppendLine("# 1. General Search Crawlers");
                sb.AppendLine("User-agent: *");
                sb.AppendLine("Allow: /");
                sb.AppendLine("Disallow: /admin/");
                sb.AppendLine("Disallow: /api/");
                sb.AppendLine();
                sb.AppendLine("# 2. Allow Live AI Search Browsers");
                sb.AppendLine("User-agent: ChatGPT-User");
                sb.AppendLine("Allow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: PerplexityBot");
                sb.AppendLine("Allow: /");
                sb.AppendLine();
                sb.AppendLine("# 3. Restrict Raw AI Model Training Scrapers");
                sb.AppendLine("User-agent: CCBot");
                sb.AppendLine("Disallow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: Bytespider");
                sb.AppendLine("Disallow: /");
                break;

            case RobotsTxtPresetEnum.BlockAiTraining:
                sb.AppendLine("# 1. General Search Crawlers (Google, Bing)");
                sb.AppendLine("User-agent: *");
                sb.AppendLine("Allow: /");
                sb.AppendLine("Disallow: /admin/");
                sb.AppendLine("Disallow: /api/");
                sb.AppendLine();
                sb.AppendLine("# 2. Block All Generative AI & Training Crawlers");
                sb.AppendLine("User-agent: GPTBot");
                sb.AppendLine("Disallow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: ChatGPT-User");
                sb.AppendLine("Disallow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: ClaudeBot");
                sb.AppendLine("Disallow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: Google-Extended");
                sb.AppendLine("Disallow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: PerplexityBot");
                sb.AppendLine("Disallow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: CCBot");
                sb.AppendLine("Disallow: /");
                sb.AppendLine();
                sb.AppendLine("User-agent: Bytespider");
                sb.AppendLine("Disallow: /");
                break;
        }

        sb.AppendLine();
        sb.AppendLine("# Sitemaps & AI Index Files");
        sb.AppendLine($"Sitemap: {sitemap}");
        sb.AppendLine($"# LLMs.txt: {llmsTxtUrl}");

        return sb.ToString();
    }
}
